AllCops:
  RunRailsCops: true
  Exclude:
    - 'Capfile'
    - 'db/seeds.rb'
    - 'bin/*'
    - 'vendor/**/*'
    - 'spec/**/*'

ClassAndModuleChildren:
  EnforcedStyle: compact

Lint/AmbiguousOperator:
  Exclude:
    - 'app/controllers/concerns/error_handling.rb'
    - 'app/models/concerns/searchable.rb'

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Metrics/ClassLength:
  Max: 180

Metrics/LineLength:
  Max: 113

PredicateName:
  NamePrefixBlacklist:
    - hoge_

inherit_from: .rubocop_todo.yml
