inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

# TODO: Remove this to enable this cop in Rails 5
# https://github.com/bbatsov/rubocop/issues/3675
Rails/HttpPositionalArguments:
  Enabled: false

AllCops:
  Exclude:
    - 'Capfile'
    - 'Gemfile'
    - 'app/validators/*'
    - 'app/models/ability.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'db/seeds.rb'
    - 'script/*'
    - 'spec/**/*'
    - 'vendor/**/*'

ClassAndModuleChildren:
  EnforcedStyle: compact

GuardClause:
  MinBodyLength: 4

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Lint/AmbiguousOperator:
  Exclude:
    - 'app/controllers/concerns/error_handling.rb'
    - 'app/models/concerns/searchable.rb'

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/UselessSetterCall:
  Exclude:
    - 'app/controllers/annotations_controller.rb'
    - 'app/controllers/note_cards_controller.rb'
    - 'app/controllers/states_controller.rb'
    - 'app/controllers/usages_controller.rb'

Metrics/ClassLength:
  Max: 180
  Exclude:
    - 'db/migrate/**'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/migrate/**'
    - 'db/schema.rb'

PredicateName:
  NamePrefixBlacklist:
    - hoge_

Style/AsciiComments:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/SignalException:
  Exclude:
    - 'app/controllers/application_controller.rb'

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false
