# rub slim-lint with following commmand
# $slim-lint app/views/ -c .slim-lint.yml

exclude: 'app/views/components/_card_figures.html.slim'

linters:
  LineLength:
    max: 160
    exclude:
      - 'app/views/annotations/_annotation.html.slim'
      - 'app/views/components/_card.html.slim'
      - 'app/views/components/_card_attachments.html.slim'
      - 'app/views/components/_card_contributors.html.slim'
      - 'app/views/components/_card_figures.html.slim'
      - 'app/views/note_cards/show.html.slim'
      - 'app/views/projects/_basic_informations.html.slim'
      - 'app/views/states/_state.html.slim'
      - 'app/views/static_pages/*.slim'
      - 'app/views/usages/_usage.html.slim'

  RuboCop:
    enabled: true
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/LineLength
      - Style/AlignHash
      - Style/AlignParameters
      - Style/BlockNesting
      - Style/FileName
      - Style/FirstParameterIndentation
      - Style/IfUnlessModifier
      - Style/IndentationConsistency
      - Style/IndentationWidth
      - Style/LineLength
      - Style/Next
      - Style/SpaceInsideHashLiteralBraces
      - Style/TrailingBlankLines
      - Style/TrailingWhitespace
      - Style/WhileUntilModifier

      - Style/StringLiterals #TODO fix sting literals
