sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1.2
services:
  - mongodb
notifications:
  slack:
    secure: <%= ENV["SLACK_NOTIFICATION_SECRET"] %>
script:
  - bundle exec rubocop --fail-level=W
