production:
  solr:
    hostname: localhost
    port: 8984
    log_level: WARNING
    path: /solr/gitfab
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 18983
    log_level: INFO
    path: /solr/gitfab2

staging:
  solr:
    hostname: localhost
    port: 8984
    log_level: INFO
    path: /solr/gitfab2_staging

test:
  solr:
    hostname: localhost
    port: 28983
    log_level: WARNING
    path: /solr/gitfab2
