default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: 127.0.0.1
  port: 13306
  username: root
  password:

development:
  <<: *default
  database: gitfab2_development

test:
  <<: *default
  database: gitfab2_test<%= ENV['TEST_ENV_NUMBER'] %>
