development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: gitfab2_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: gitfab2_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
