default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV.fetch('DB_HOST') { "localhost" } %>
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>
  username: <%= ENV.fetch('DB_USERNAME') { "root" } %>
  password: <%= ENV.fetch('DB_PASSWORD') { "" } %>

development:
  <<: *default
  database: gitfab2_development

test:
  <<: *default
  database: gitfab2_test<%= ENV['TEST_ENV_NUMBER'] %>
